### PR TITLE
added AdditionalUnits mod support

### PR DESCRIPTION
**Pull request by 4c65736975**

### CODE REVIEW

**Review by Achimobil — CHANGES_REQUESTED** [review]
I dont know such a mod. So rejected.
- who are you?
- where is the mod Hub link to that mod?
Then I will think if I want a support for it in my mod

**Comment by 4c65736975** [comment]
> I dont know such a mod. So rejected.
> 
> * who are you?
> * where is the mod Hub link to that mod?
>   Then I will think if I want a support for it in my mod

I'm VertexFloat, author of this [mods ](https://www.farming-simulator.com/mods.php?org_id=140307)

These changes are intended to make this mod to work with [AdditionalUnits](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=268900&title=fs2022)

**Comment by Achimobil** [comment]
Nice to meet you. I'll take a look at your changes and your mod, looks not bad. 
Have you tested that the changes are working also when your mod is not available and when it is available?

**Comment by 4c65736975** [comment]
> Nice to meet you. I'll take a look at your changes and your mod, looks not bad. Have you tested that the changes are working also when your mod is not available and when it is available?

Thanks, you too. Yes, I tested with and without the modification, everything worked properly. When you test/check, please download version 1.0.0.1 from [github](https://github.com/VertexFloat/additionalUnits), because this update has not been released on modhub yet (waiting for testing)

**Comment by Achimobil** [comment]
I will merge the changes to my mod and make a beta release available here in github. I self will test it in SP and MP without your mod and you can link the version on your github so your users can test with. Ok?

**Review by Achimobil — APPROVED** [review]
Changes looks good so far. So merging to main for new beta version

**Comment by 4c65736975** [comment]
> I will merge the changes to my mod and make a beta release available here in github. I self will test it in SP and MP without your mod and you can link the version on your github so your users can test with. Ok?

Thanks. Sure, I'll add a link to InfoDisplayExtension in this version, in the README file. So that people know that they can test with this version. Is that what you mean?

**Comment by Achimobil** [comment]
yes, or in the ticket where the report is in. How you want.
https://github.com/Achimobil/FS22_InfoDisplayExtension/releases/tag/1.7.1.1

**Pull request merged**
